# GitHub Action for PHP with extensions
name: macOS

on: [push, pull_request]

jobs:
  macos:
    name: macOS CI
    runs-on: macos-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        operating-system: [macos-latest]
        php-versions: ['7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install libuv and PHP build tools
        run: |
          brew install libuv
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: curl, fileinfo, mbstring, openssl, simplexml, dom, sockets, sodium, uv-beta, xdebug
          coverage: xdebug
      - name: Install dependencies
        run: composer install
      - name: Test with phpunit
        run: vendor/bin/phpunit --coverage-clover=coverage.xml
      - name: Submit code coverage
        if: ${{ success() }} || ${{ failure() }}
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml # optional
